---
title: "Analyze luminescent data to create figure 5A"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

# Load libraries

```{r}
library(tidyverse)
library(rasilabRtemplates)
library(plotrix)

theme_rasilab <- function() {
  theme_classic(base_family = "Helvetica", base_size = 8) +
    theme(
      strip.background = ggplot2::element_blank(),
      legend.text = element_text(size = 8),
      strip.text.x = element_text(size = 8),
      axis.line = element_line(color = "black", size=.25),
      axis.text = element_text(color = "black", size = 8)
    )
}

theme_set(theme_rasilab())
```

# Read in data

```{r}
counts <- read_tsv("../rawdata/20191223_fluc_nluc.tsv") %>%
  print()
```

# Read in annotationsl

```{r}
annotations <- read_tsv("../annotations/sampleannotations.tsv") %>%
  print()
```

# Join data with annotations, normalize NLuc by FLuc, calculate mean and error

```{r}
data <- counts %>% 
  pivot_wider(names_from = assay, values_from = counts) %>%
  left_join(annotations, by = "well") %>%
  mutate(fluc = fluc - mean(fluc[reporter == "mock"]), nluc = nluc - mean(nluc[reporter == "mock"])) %>%
  filter(label != "mock") %>% 
  mutate(ratio = log2(nluc) - log2(fluc)) %>% 
  group_by(reporter) %>% 
  mutate(mean_ratio = mean(ratio), se_ratio = std.error(ratio)) %>% 
  slice(1) %>% 
  ungroup() %>% 
  select(-well, -fluc, -nluc, -ratio, -replicate) %>%
  arrange(desc(status)) %>% 
  mutate(label = str_replace(label, "GC", "")) %>% 
  mutate(label = str_replace(label, "CAA repeat", "no SL")) %>% 
  mutate(label = fct_reorder(label, label_order)) %>%
  mutate(status = fct_reorder(status, status_order)) %>%
  print()
```
# Plot Fluc / Nluc

```{r, fig.width=2.5, fig.height=1.25}
plot_data <- data %>%
  mutate(mean_ratio = mean_ratio - max(mean_ratio)) %>%
  filter(!is.na(status)) %>% 
  print()

plot_data %>%
# Plot average nluc/fluc ratios by reporter construct
 ggplot(aes(x = label, y = mean_ratio, ymax = mean_ratio + se_ratio,
            ymin = mean_ratio - se_ratio, color = status, shape = status)) +  
  geom_point(size = 2) +
  geom_errorbar(width = 0.5, show.legend = F) +
  labs(y = 'NLuc / FLuc\n(log2, a.u.)',
       x = 'stem loop GC %') +
  scale_y_continuous(breaks = scales::pretty_breaks(n=3)) +
  coord_flip() +
  theme(axis.text.y = element_text(size = 7), axis.text.x = element_text(size = 7)) +
  scale_color_manual(values = cbPalette[c(2,1)])

ggsave("../figures/fig_5a_left.pdf")
```

```{r, fig.width=0.75, fig.height=1.25}
plot_data <- data %>%
  mutate(mean_ratio = mean_ratio - max(mean_ratio)) %>%
  filter(!is.na(status)) %>%
  group_by(label) %>%
  mutate(mean_ratio = mean_ratio - mean_ratio[status=="no stall"]) %>%
  ungroup() %>%
  filter(status == 'WT') %>%
  print()

plot_data %>%
# Plot average nluc/fluc ratios by reporter construct
 ggplot(aes(x = label, y = mean_ratio, ymax = mean_ratio + se_ratio,
            ymin = mean_ratio - se_ratio)) +  
  geom_point(size = 1) +
  geom_errorbar(width = 0.5, show.legend = F) +
  labs(y = 'WT / no stall\n(ratio)',
       x = 'stem loop GC %') +
  scale_y_continuous(breaks = scales::pretty_breaks(n=2)) +
  coord_flip() +
  theme(axis.text.y = element_blank(), axis.text.x = element_text(size = 7), axis.title.y = element_blank())
  scale_color_manual(values = cbPalette[c(2,1)])

ggsave("../figures/fig_5a_right.pdf")
```