name: R
channels:
  - conda-forge
  - defaults
dependencies:
  - r-tidyverse
  - r-irkernel
  - r-viridis
  - r-devtools
  - r-janitor
  - r-plotrix
  - r-rtracklayer
  - r-GenomicFeatures
  - r-Biostrings
  - r-plyranges