---
title: "Analyze luminescent data from UL4 uORF2 mutants to create figure 6C"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

# Load libraries

```{r}
library(plotrix)
library(tidyverse)
library(rasilabRtemplates)

theme_rasilab <- function() {
  theme_classic(base_family = "Helvetica", base_size = 8) +
    theme(
      strip.background = ggplot2::element_blank(),
      legend.text = element_text(size = 8),
      strip.text.x = element_text(size = 8),
      axis.line = element_line(color = "black", size=.25),
      axis.text = element_text(color = "black", size = 8)
    )
}

theme_set(theme_rasilab())
```

# Read in data

```{r}
counts <- read_csv("../rawdata/20220413_fluc_nluc.csv") %>%
  print()
```

# Read in annotations

```{r}
annotations <- read_csv("../annotations/sampleannotations.csv") %>%
  print()
```

# Join data with annotations, normalize NLuc by FLuc, calculate mean and error

```{r}
data <- counts %>% 
  pivot_wider(names_from = assay, values_from = counts) %>%
  left_join(annotations, by = "well") %>%
  mutate(fluc = fluc - mean(fluc[reporter == "mock"]), nluc = nluc - mean(nluc[reporter == "mock"])) %>%
  filter(label != "mock") %>% 
  mutate(ratio = log2(nluc) - log2(fluc)) %>% 
  group_by(reporter) %>% 
  mutate(mean_ratio = mean(ratio), se_ratio = std.error(ratio)) %>%
  slice(1) %>% 
  ungroup() %>% 
  select(-well, -fluc, -nluc, -ratio, -replicate) %>%
  mutate(label = fct_reorder(label, label_order)) %>%
  print()
```

# Plot FLuc / NLuc

```{r, fig.width=3.6, fig.height=1}
plot_data <- data %>%
  mutate(mean_ratio = mean_ratio - mean_ratio[label=="gp48UTR-no-AUG"]) %>%
  filter(reporter %in% c("pTBHS12", "pTBHS13", "pTBHS23", "pTBHS24", "pTBHS58", "pTBHS59", "pTBHS60", "pTBHS61")) %>%
  print()

plot_data %>%
# Plot average nluc/fluc ratios by reporter construct
 ggplot(aes(x = label, y = mean_ratio, ymax = mean_ratio + se_ratio,
            ymin = mean_ratio - se_ratio, color = P22A, shape = P22A)) +  
  geom_point(size = 2) +
  geom_errorbar(width = 0.5, show.legend = F) +
  labs(y = 'NLuc / FLuc\n(log2, a.u.)',
       x = '') +
  scale_y_continuous(breaks = scales::pretty_breaks(n=3)) +
  scale_color_manual(values = cbPalette[c(2,1)]) +
  scale_shape_manual(values=c(17, 16)) +
  coord_flip() +
  theme(axis.text.y = element_text(size = 7), axis.text.x = element_text(size = 7))
ggsave("../figures/fig_6c.pdf")
```