---
title: "Analyze luminescent data from perturbed uORF2 d_stall mutants to create figure 6B"
output: 
  github_document:
    toc: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

# Load libraries

```{r}
library(tidyverse)
library(rasilabRtemplates)
library(plotrix)

theme_rasilab <- function() {
  theme_classic(base_family = "Helvetica", base_size = 8) +
    theme(
      strip.background = ggplot2::element_blank(),
      legend.text = element_text(size = 8),
      strip.text.x = element_text(size = 8),
      axis.line = element_line(color = "black", size=.25),
      axis.text = element_text(color = "black", size = 8)
    )
}

theme_set(theme_rasilab())
```

# Read in data

```{r}
counts <- read_csv("../rawdata/20190829_fluc_nluc.csv") %>%
  print()
```

# Read in annotations

```{r}
annotations <- read_csv("../annotations/sampleannotations.csv") %>%
  janitor::clean_names() %>% 
  print()
```

# Join data with annotations, normalize NLuc by FLuc, calculate mean and error

```{r}
data <- counts %>% 
  pivot_wider(names_from = assay, values_from = counts) %>%
  left_join(annotations, by = "well") %>%
  mutate(fluc = fluc - mean(fluc[reporter == "mock"]), nluc = nluc - mean(nluc[reporter == "mock"])) %>%
  filter(fluc > 0) %>% 
  filter(label != "mock") %>%
  mutate(ratio = log2(nluc) - log2(fluc)) %>% 
  group_by(reporter) %>% 
  mutate(mean_ratio = mean(ratio), se_ratio = std.error(ratio)) %>% 
  slice(1) %>%
  ungroup() %>% 
  select(-well, -fluc, -nluc, -ratio, -replicate) %>%
  mutate(label = fct_reorder(label, label_order)) %>%
  print()
```

# Plot Fluc / Nluc for subset samples 

```{r, fig.width=2.6, fig.height=1.7}
plot_data <- data %>%
  # select only reporters of interest
  filter(!is.na(label_order)) %>% 
  mutate(mean_ratio = mean_ratio - max(mean_ratio)) %>%
  print()

plot_data %>%
# Plot average nluc/fluc ratios by reporter construct
 ggplot(aes(y = label, x = mean_ratio, xmax = mean_ratio + se_ratio,
            xmin = mean_ratio - se_ratio)) +
  geom_point(size = 1) +
  geom_errorbar(width = 0.5, show.legend = F) +
  labs(x = 'NLuc / FLuc (log2 a.u.)', y = '', color = '') +
  scale_x_continuous(breaks = scales::pretty_breaks(n=4)) +
  theme(panel.grid = element_blank(), axis.text.y = element_text(size = 7), axis.text.x = element_text(size = 7))

ggsave("../figures/fig_6b.pdf")
```