---
title: "Analyze luminescent data from UL4 uORF2 mutants to create figure 5B"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

# Load libraries

```{r}
library(plotrix)
library(tidyverse)
library(rasilabRtemplates)
```

# Read in data

```{r}
counts <- read_csv("../rawdata/20220612_fluc_nluc.csv") %>%
  print()
```

# Read in annotations

```{r}
annotations <- read_csv("../annotations/sampleannotations.csv") %>%
  print()
```

# Join data with annotations, normalize NLuc by FLuc, calculate mean and error

```{r}
data <- counts %>% 
  pivot_wider(names_from = assay, values_from = counts) %>%
  left_join(annotations, by = "well") %>%
  mutate(fluc = fluc - mean(fluc[reporter == "mock"]), nluc = nluc - mean(nluc[reporter == "mock"])) %>%
  filter(label != "mock") %>%
  filter(fluc > 0) %>%
  mutate(ratio = log2(nluc) - log2(fluc)) %>% 
  group_by(reporter, status) %>% 
  mutate(mean_ratio = mean(ratio), se_ratio = std.error(ratio)) %>% 
  ungroup() %>%
  select(-well, -fluc, -nluc, -replicate) %>%
  #mutate(label = fct_rev(fct_reorder(label, label_order))) %>%
  print()
```

# Import uORF2 mutant data for normalization

```{r}

norm_data <- read_csv("../../20190422_exp2_ul4_mutants/tables/nluc_fluc_control_mutants_not_normalized.csv") %>%
  filter(label == "gp48UTR-no-AUG") %>%
  print()

```

# Plot FLuc / NLuc for drug treatment

```{r, fig.width=2.3, fig.height=1}
plot_data <- data %>%
  mutate(mean_ratio = mean_ratio - norm_data$mean_ratio) %>%
  print()

plot_data$label <- factor(plot_data$label, levels = c("WT", "No-stall"))

plot_data %>%
# Plot average nluc/fluc ratios by reporter construct
 ggplot(aes(x = status, y = mean_ratio, ymax = mean_ratio + se_ratio,
            ymin = mean_ratio - se_ratio, color = label, shape = label)) +  
  geom_point(size = 2) +
  geom_errorbar(width = 0.5, show.legend = F) +
  labs(y = 'NLuc / FLuc\n(log2, a.u.)',
       x = 'ER stressor') +
  scale_y_continuous(breaks = scales::pretty_breaks(n=3)) +
  coord_flip() +
  theme(axis.text.y = element_text(size = 7), axis.text.x = element_text(size = 7)) +
  scale_color_manual(values = cbPalette[c(2,1)])

ggsave("../figures/fig_5b_left.pdf")
```

# Plot FLuc / NLuc for drug treatment, normalized

```{r, fig.width=0.75, fig.height=1}
plot_data <- data %>%
  #mutate(mean_ratio = mean_ratio - norm_data$mean_ratio) %>%
  group_by(status) %>%
  mutate(mean_ratio = mean_ratio - mean_ratio[label=="No-stall"]) %>%
  ungroup() %>%
  filter(label == 'WT') %>%
  print()

plot_data %>%
# Plot average nluc/fluc ratios by reporter construct
 ggplot(aes(x = status, y = mean_ratio, ymax = mean_ratio + se_ratio,
            ymin = mean_ratio - se_ratio)) +  
  geom_point(size = 1) +
  geom_errorbar(width = 0.5, show.legend = F) +
  labs(y = 'WT / no stall\n(ratio)',
       x = '') +
  scale_y_continuous(breaks = scales::pretty_breaks(n=2)) +
  scale_color_manual(values = cbPalette[c(2,1)]) +
  coord_flip() +
  theme(axis.text.y = element_blank(), axis.text.x = element_text(size = 7), axis.title.y = element_blank())

ggsave("../figures/fig_5b_right.pdf")
```

# Conclusions

 - 
